apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: nginx
      env:
        - name: "ENV"
          value: "dev"
      ports:
        - name: web
          containerPort: 80
          protocol: TCP